#!/usr/bin/env python3

# Copyright 2025 Rafal Maziejuk
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import sys

from tools import (
    copyright,
    format,
    tidy,
)

def parse_command_line_args():
    """
    Parses command-line arguments. Adds subparsers to the main parser.

    Returns:
        args:
            arguments parsed from command-line
    """
    parser = argparse.ArgumentParser(description='NTL CLI tool',
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    subparsers = parser.add_subparsers(help='Commands (<command> -h for command help)',
                                       dest='command')
    
    for module in [
        copyright,
        format,
        tidy,
    ]:
        module.add_subparsers(subparsers)

    args = parser.parse_args()
    if 'func' not in args:
        parser.print_help()
        sys.exit()

    return args

if __name__ == '__main__':
    try:
        args = parse_command_line_args()
        return_code = args.func(args)
        if return_code is not None:
            sys.exit(return_code)
    except KeyboardInterrupt:
        print('\nCancelled')
